# permissions for end users to view assettypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assettype-viewer-role
rules:
- apiGroups:
  - application.apollo.microsoft.com
  resources:
  - assettypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.apollo.microsoft.com
  resources:
  - assettypes/status
  verbs:
  - get
