# permissions for end users to edit moduletypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moduletype-editor-role
rules:
- apiGroups:
  - application.apollo.microsoft.com
  resources:
  - moduletypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.apollo.microsoft.com
  resources:
  - moduletypes/status
  verbs:
  - get
