apiVersion: v1
kind: Service
metadata:
  name: opc-ua-discovery
  namespace: akri
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: opc-ua-discovery
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: opc-ua-discovery
  name: opc-ua-discovery
  namespace: akri
spec:
  containers:
    - name: opc-ua-discovery
      image: edgeappmodel.azurecr.io/opcua-discovery-handler
      ports:
      - containerPort: 80
      resources: {}
  imagePullSecrets:
  - name: edgeappmodel
  - name: edgeappmodel-azurecr
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}