

# Credential #1
# username: umati1
# password: umati 
[umati1]
password = "umati"


[umati1.attributes]
site = "Redmond"
organization = "manufacturing"


[umati2]
password = "umati"


[umati2.attributes]
site = "Boulder"
