
[mqttclient1]
password = ""


[mqttclient1.attributes]
group = "factory_1"
organization = "manufacturing"


[mqttclient2]
password = ""


[mqttclient2]
group = "factory_2"
organization = "process"