e4kdmqtt:
  broker:
    frontend:
      replicas: 2 
    backend:
      replicas: 2 
      chainCount: 2 

connector:
  enabled: true

e4kconnector:
  kafka:
    # Port 9093 is Event Hub's Kakfa endpoint
    endpoint: <NAMESPACE>.servicebus.windows.net:9093
    # Kafka consumer group id prefix
    # Unique for every route that sinks from Kafka to E4K
    group_id_prefix: e4kconnector
    # Interval to commit consumer reading offset position to Kafka broker
    auto_commit_interval_ms: 5000
    listener:
      # Event Hub uses SSL
      type: ssl
      # Event Hub uses SASL PLAIN authentication for its Kafka-compatible endpoint
      sasl:
        sasl_type: plain
        username: $ConnectionString
        password: Endpoint=sb://<NAMESPACE>.servicebus.windows.net/;SharedAccessKeyName=<KEY_NAME>;SharedAccessKey=<KEY>
  topicMap:
    configYaml:
      route:
        # Pull from MQTT topic "cnc-fab-telemetry" and push to Kafka topic "<RECEIVING_EH_NAME>"
        # Default partition 0 only
        - kafka: telemetry
          mqtt: cnc-fab-telemetry
          sink_to: kafka
        
    