e4kdmqtt:
  broker:
    frontend:
      replicas: 2 
    backend:
      replicas: 2 
      chainCount: 2 

connector:
  enabled: true 

e4kconnector:
  kafka:
    endpoint: ;;;
    group_id_prefix: e4kconnector 
    auto_commit_interval_ms: 5000
    