apiVersion: v1
kind: Secret
metadata:
  name: edgeappmodel-azurecr
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJlZGdlYXBwbW9kZWwuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6IkVkZ2VBcHBNb2RlbCIsInBhc3N3b3JkIjoiSzlmT3BJNHZKVkR3bWRpQXFQTj14WHVKR255ZGpjREQiLCJhdXRoIjoiUldSblpVRndjRTF2WkdWc09rczVaazl3U1RSMlNsWkVkMjFrYVVGeFVFNDllRmgxU2tkdWVXUnFZMFJFIn19fQ==
type: kubernetes.io/dockerconfigjson