apiVersion: apps/v1
kind: Deployment 
metadata:
  name: opcplc-deployment
  labels:
    app: opcplc
spec:
  selector: 
    matchLabels:
      app: opcplc 
  template:
    spec:
      containers:
        - name: opcplc 
          image: mcr.microsoft.com/iotedge/opc-plc:latest
          args: [""]
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          ports: 
            - containerPort: 50000
            - containerPort: 8080
          
# --sph --sn=5 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --ctb --scn --lid --lsn --ref --gn=5
---

apiVersion: v1
kind: Service 
metadata:
  name: opcplc-service 
spec: 
  selector:
    app.kubernetes.io/name: opcplc
  ports:
    - protocol: TCP 
      port: 50000
      targetPort: 50000
    - protocol: TCP
      port: 8080
      targetPort: 8080 
