apiVersion: v1
kind: Service
metadata:
  name: opcplc-service
spec:
  type: NodePort
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: opc-plc
status:
  loadBalancer: {}

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opc-plc 
  name: opcplc-deployment
spec:
  selector:
    matchLabels:
      app: opc-plc
  template:
    metadata:
      labels: 
        app: opc-plc
    spec:
      containers:
        - name: opcplc 
          image: mcr.microsoft.com/iotedge/opc-plc:latest
          args:
            - "--sph"
            - "--sp"
            - "--sn=5"
            - "--sr=10"
            - "--st=uint"
            - "--fn=5"
            - "--fr=1"
            - "--ft=uint"
            - "--ctb"
            - "--scn"
            - "--lid"
            - "--lsn"
            - "--ref"
            - "--gn=5"
            - "--aa"
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          ports: 
            - containerPort: 50000
            - containerPort: 8080
